name: Bug-Report
description: Bug-Report mit URL, Request- und Response-Body
title: "[BUG] "
labels: [bug]
body:
  - type: input
    id: bug-title
    attributes:
      label: Titel des Bugs
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Beschreibung
    validations:
      required: true

  - type: input
    id: bug-url
    attributes:
      label: URL
    validations:
      required: true

  - type: textarea
    id: request-body
    attributes:
      label: Request Body
      render: json

  - type: textarea
    id: response-body
    attributes:
      label: Response Body
      render: json
