name: Feature-Request
description: Schlage ein neues Feature oder eine Verbesserung vor.
title: "[FEATURE] "
labels: [feature]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description
    validations:
      required: true
